src/Entity/Menu.php
<?php

namespace TwinElements\MenuBundle\Entity;

use TwinElements\AdminBundle\Entity\Traits\IdTrait;
use TwinElements\SortableBundle\Entity\PositionInterface;
use TwinElements\SortableBundle\Model\PositionTrait;
use Doctrine\ORM\Mapping as ORM;
use Knp\DoctrineBehaviors\Contract\Entity\BlameableInterface;
use Knp\DoctrineBehaviors\Contract\Entity\LoggableInterface;
use Knp\DoctrineBehaviors\Contract\Entity\TimestampableInterface;
use Knp\DoctrineBehaviors\Contract\Entity\TranslatableInterface;
use Knp\DoctrineBehaviors\Model\Blameable\BlameableTrait;
use Knp\DoctrineBehaviors\Model\Loggable\LoggableTrait;
use Knp\DoctrineBehaviors\Model\Timestampable\TimestampableTrait;
use Knp\DoctrineBehaviors\Model\Translatable\TranslatableTrait;

/**
 * @ORM\Entity(repositoryClass="TwinElements\MenuBundle\Repository\MenuRepository")
 * @ORM\Table(name="menu")
 */
class Menu implements TranslatableInterface, BlameableInterface, TimestampableInterface, LoggableInterface, PositionInterface
{
    use
        IdTrait,
        PositionTrait,
        TranslatableTrait,
        BlameableTrait,
        TimestampableTrait,
        LoggableTrait;

    /**
     * @ORM\ManyToOne(targetEntity="TwinElements\MenuBundle\Entity\MenuCategory")
     * @ORM\JoinColumn(name="category_id",referencedColumnName="id", onDelete="CASCADE")
     */
    private $category;

    /**
     * @ORM\OneToMany(targetEntity="TwinElements\MenuBundle\Entity\Menu", mappedBy="parent", cascade={"all"}, orphanRemoval=true)
     * @ORM\OrderBy({"position" = "ASC"})
     */
    private $children;

    /**
     * @ORM\ManyToOne(targetEntity="TwinElements\MenuBundle\Entity\Menu", inversedBy="children")
     * @ORM\JoinColumn(name="parent_id", referencedColumnName="id", onDelete="CASCADE")
     */
    private $parent;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isInNewTab = false;

    /**
     * @var boolean
     * @ORM\Column(type="boolean")
     */
    private $isMegamenu = false;

    public function __toString()
    {
        $title = $this->translate(null, false)->getTitle();

        if ($title) {
            return $title;
        } else {
            return 'no translation';
        }
    }

    public function getTitle(): ?string
    {
        return $this->translate(null, false)->getTitle();
    }

    public function setTitle(string $title): void
    {
        $this->translate(null, false)->setTitle($title);
    }

    /**
     * @return mixed
     */
    public function getCategory()
    {
        return $this->category;
    }

    /**
     * @param mixed $category
     */
    public function setCategory($category): void
    {
        $this->category = $category;
    }

    /**
     * @return mixed
     */
    public function getChildren()
    {
        return $this->children;
    }

    /**
     * @param mixed $children
     */
    public function setChildren($children): void
    {
        $this->children = $children;
    }

    /**
     * @return mixed
     */
    public function getParent()
    {
        return $this->parent;
    }

    /**
     * @param mixed $parent
     */
    public function setParent($parent): void
    {
        $this->parent = $parent;
    }


    /**
     * @return bool
     */
    public function isInNewTab(): bool
    {
        return $this->isInNewTab;
    }

    /**
     * @param bool $isInNewTab
     */
    public function setIsInNewTab(bool $isInNewTab): void
    {
        $this->isInNewTab = $isInNewTab;
    }


    /**
     * @return mixed
     */
    public function getRoute()
    {
        return $this->translate(null, false)->getRoute();
    }

    /**
     * @param mixed $route
     */
    public function setRoute($route): void
    {
        $this->translate(null, false)->setRoute($route);
    }

    /**
     * @return bool
     */
    public function isMegamenu(): bool
    {
        return $this->isMegamenu;
    }

    /**
     * @param bool $isMegamenu
     */
    public function setIsMegamenu(bool $isMegamenu): void
    {
        $this->isMegamenu = $isMegamenu;
    }
}

src/Form/MenuType.php
<?php

namespace TwinElements\MenuBundle\Form;

use Doctrine\ORM\EntityRepository;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use TwinElements\Component\AdminTranslator\AdminTranslator;
use TwinElements\FormExtensions\Type\SaveButtonsType;
use TwinElements\FormExtensions\Type\TEChooseLinkType;
use TwinElements\FormExtensions\Type\ToggleChoiceType;
use TwinElements\MenuBundle\Entity\Menu;

class MenuType extends AbstractType
{
    /**
     * @var AdminTranslator $translator
     */
    private $translator;

    public function __construct(AdminTranslator $translator)
    {
        $this->translator = $translator;
    }

    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title', TextType::class, [
                'label' => $this->translator->translate('admin.title')
            ])
            ->add('route', TEChooseLinkType::class, [
                'label' => $this->translator->translate('menu.redirect')
            ])
            ->add('parent', EntityType::class, [
                'class' => Menu::class,
                'query_builder' => function (EntityRepository $entityRepository) use ($options) {
                    $qb = $entityRepository->createQueryBuilder('m');
                    $qb
                        ->select(['m', 'm_translations'])
                        ->join('m.translations', 'm_translations');

                    if (is_numeric($options['category'])) {
                        $qb
                            ->where('m.category = :category')
                            ->setParameter('category', $options['category']);
                    }

                    return $qb;
                },
                'label' => $this->translator->translate('menu.parent'),
                'label_attr' => ['class' => 'col-md-3 col-lg-2'],
                'attr' => [
                    'class' => 'col-md-4 input'
                ],
                'placeholder' => $this->translator->translate('menu.choose_parent'),
                'required' => false
            ])
            ->add('isInNewTab', ToggleChoiceType::class, [
                'label' => $this->translator->translate('menu.open_in_a_new_tab'),
                'help' => $this->translator->translate('menu.open_in_a_new_tab_help')
            ])
            ->add('isMegamenu', ToggleChoiceType::class,[
                'label' => $this->translator->translate('menu.is_mega_menu')
            ])
            ->add('buttons', SaveButtonsType::class);
    }

    /**
     * {@inheritdoc}
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => Menu::class,
            'category' => null
        ));
    }

    /**
     * {@inheritdoc}
     */
    public function getBlockPrefix()
    {
        return 'app_menu';
    }
}

src/Controller/MenuController.php
<?php

namespace TwinElements\MenuBundle\Controller;

use Symfony\Component\Cache\Adapter\AdapterInterface;
use TwinElements\Component\CrudLogger\CrudLogger;
use TwinElements\Component\CrudLogger\CrudLoggerInterface;
use TwinElements\SortableBundle\Entity\PositionInterface;
use TwinElements\AdminBundle\Helper\Breadcrumbs;
use TwinElements\AdminBundle\Model\CrudControllerTrait;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Request;
use TwinElements\AdminBundle\Role\AdminUserRole;
use TwinElements\Component\AdminTranslator\AdminTranslator;
use TwinElements\Component\Flashes\Flashes;
use TwinElements\MenuBundle\Entity\Menu;
use TwinElements\MenuBundle\Entity\MenuCategory;
use TwinElements\MenuBundle\Form\MenuType;
use TwinElements\MenuBundle\MenuCacheUtilities;
use TwinElements\MenuBundle\Repository\MenuCategoryRepository;
use TwinElements\MenuBundle\Repository\MenuRepository;

/**
 * @Route("menu")
 */
class MenuController extends AbstractController
{
    /**
     * @var AdapterInterface $cache
     */
    private $cache;

    use CrudControllerTrait {
        CrudControllerTrait::__construct as private __crudConstruct;
    }

    public function __construct(Breadcrumbs $breadcrumbs, Flashes $flashes, CrudLoggerInterface $crudLogger, AdminTranslator $translator, AdapterInterface $cache)
    {
        $this->__crudConstruct($breadcrumbs, $flashes, $crudLogger, $translator);
        $this->cache = $cache;
    }

    /**
     * @Route("/", name="menu_index", methods={"GET"})
     */
    public function indexAction(Request $request, MenuRepository $menuRepository, MenuCategoryRepository $menuCategoryRepository)
    {
        if (!$request->query->has('category')) {
            throw new \Exception('Category ID not found');
        }

        $categoryId = $request->query->getInt('category');

        $menuItems = $menuRepository->findIndexListItems($categoryId);
        $menuCategory = $menuCategoryRepository->find($categoryId);

        $this->breadcrumbs->setItems([
            $this->adminTranslator->translate('menu_category.menu_categories') => $this->generateUrl('menucategory_index'),
            $menuCategory->getTitle() => null
        ]);

        $responseParameters = [
            'menus' => $menuItems,
            'menu_category' => $menuCategory
        ];

        if ((new \ReflectionClass(Menu::class))->implementsInterface(PositionInterface::class)) {
            $responseParameters['sortable'] = Menu::class;
        }

        return $this->render('@TwinElementsMenu/menu/index.html.twig', $responseParameters);
    }

    /**
     * @Route("/new", name="menu_new", methods={"GET", "POST"})
     */
    public function newAction(Request $request, AdapterInterface $cache)
    {
        $this->denyAccessUnlessGranted(AdminUserRole::ROLE_ADMIN);

        $categoryId = (int)$request->get('category');
        $menuCategory = $this->getDoctrine()->getRepository(MenuCategory::class)->find($categoryId);

        $menuCategoryDefaultTitle = $menuCategory->getTitle();

        $menu = new Menu();
        $menu->setCurrentLocale($request->getLocale());
        $form = $this->createForm(MenuType::class, $menu, ['category' => $categoryId]);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            try {

                $menu->setCategory($menuCategory);

                $em = $this->getDoctrine()->getManager();

                $em->persist($menu);
                $menu->mergeNewTranslations();

                $em->flush();

                if ($menuCategory->isCached()) {
                    $this->removeCache($menuCategory->getId(), $request->getLocale());
                }

                $this->flashes->successMessage($this->adminTranslator->translate('admin.success_operation'));;
                $this->crudLogger->createLog(Menu::class, CrudLogger::CreateAction, $menu->getId());

            } catch (\Exception $exception) {
                $this->flashes->errorMessage($exception->getMessage());
                return $this->redirectToRoute('menu_index', array('category' => $menuCategory->getId()));
            }

            if ('save' === $form->getClickedButton()->getName()) {
                return $this->redirectToRoute('menu_edit', array('id' => $menu->getId(), 'category' => $menuCategory->getId()));
            } else {
                return $this->redirectToRoute('menu_index', array('category' => $menuCategory->getId()));
            }
        }


        $this->breadcrumbs->setItems([
            $this->adminTranslator->translate('menu_category.menu_categories') => $this->generateUrl('menucategory_index'),
            $menuCategoryDefaultTitle => $this->generateUrl('menu_index', [
                'category' => $categoryId
            ]),
            'Dodawanie nowej pozycji' => null
        ]);

        return $this->render('@TwinElementsMenu/menu/new.html.twig', array(
            'menu' => $menu,
            'menu_category' => $menuCategory,
            'form' => $form->createView(),
            'menu_category_default_locale_title' => $menuCategoryDefaultTitle
        ));
    }

    /**
     * @Route("/{id}/edit", name="menu_edit", methods={"GET", "POST"})
     */
    public function editAction(Request $request, Menu $menu, AdapterInterface $cache)
    {
        $this->denyAccessUnlessGranted(AdminUserRole::ROLE_ADMIN);

        $categoryId = (int)$request->get('category');

        $menuCategory = $menu->getCategory();

        $deleteForm = $this->createDeleteForm($menu);
        $editForm = $this->createForm(MenuType::class, $menu, ['category' => $categoryId]);
        $editForm->handleRequest($request);

        if ($editForm->isSubmitted() && $editForm->isValid()) {

            try {
                $menu->mergeNewTranslations();

                $this->getDoctrine()->getManager()->flush();

                if ($menuCategory->isCached()) {
                    $this->removeCache($menuCategory->getId(), $request->getLocale());
                }

                $this->flashes->successMessage($this->adminTranslator->translate('admin.success_operation'));;
                $this->crudLogger->createLog(Menu::class, CrudLogger::EditAction, $menu->getId());

            } catch (\Exception $exception) {
                $this->flashes->errorMessage($exception->getMessage());
            }

            if ('save' === $editForm->getClickedButton()->getName()) {
                return $this->redirectToRoute('menu_edit', array('id' => $menu->getId(), 'category' => $menuCategory->getId()));
            } else {
                return $this->redirectToRoute('menu_index', array('category' => $menuCategory->getId()));

            }
        }

        $this->breadcrumbs->setItems([
            $this->adminTranslator->translate('menu_category.menu_categories') => $this->generateUrl('menucategory_index'),
            $menu->getCategory()->getTitle() => $this->generateUrl('menu_index', [
                'category' => $categoryId
            ]),
            $menu->getTitle() => null
        ]);

        return $this->render('@TwinElementsMenu/menu/edit.html.twig', array(
            'entity' => $menu,
            'menu_category' => $menuCategory,
            'form' => $editForm->createView(),
            'delete_form' => $deleteForm->createView()
        ));
    }

    /**
     * Deletes a menu entity.
     *
     * @Route("/{id}", name="menu_delete", methods={"DELETE"})
     */
    public function deleteAction(Request $request, Menu $menu)
    {
        $this->denyAccessUnlessGranted(AdminUserRole::ROLE_ADMIN);

        $form = $this->createDeleteForm($menu);
        $form->handleRequest($request);

        $category = $menu->getCategory()->getId();

        if ($form->isSubmitted() && $form->isValid()) {

            try {
                $id = $menu->getId();
                $em = $this->getDoctrine()->getManager();
                $em->remove($menu);
                $em->flush();

                $this->removeCache($category, $request->getLocale());

                $this->crudLogger->createLog(Menu::class, CrudLogger::DeleteAction, $id);
                $this->flashes->successMessage($this->adminTranslator->translate('menu.the_menu_item_has_been_deleted'));
            } catch (\Exception $exception) {
                $this->flashes->errorMessage($exception->getMessage());
            }
        }

        return $this->redirectToRoute('menu_index', ['category' => $category]);
    }

    /**
     * Creates a form to delete a menu entity.
     *
     * @param Menu $menu The menu entity
     *
     * @return \Symfony\Component\Form\Form The form
     */
    private function createDeleteForm(Menu $menu)
    {
        return $this->createFormBuilder()
            ->setAction($this->generateUrl('menu_delete', array('id' => $menu->getId(), 'category' => $menu->getCategory()->getId())))
            ->setMethod('DELETE')
            ->getForm();
    }

    private function removeCache(int $id, string $locale)
    {
        if ($this->cache->hasItem(MenuCacheUtilities::getCacheName($id, $locale))) {
            $this->cache->deleteItem(MenuCacheUtilities::getCacheName($id, $locale));
        }
    }
}

src/templates/menu/ajax_item_list.html.twig
<select id="itemList" class="input form-control" style="margin-top: 20px;">
    <option>Wybierz z listy</option>
    {% for item in items %}
        <option value="{{ item.id }}" {% if checkedKey == item.id %}selected="selected"{% endif %}>{{ item.title }}</option>
    {% endfor %}
</select>

src/templates/menu/edit.html.twig
{% extends '@TwinElementsAdmin/core/details_with_sidebar.html.twig' %}

{% set back_button_link = path('menu_index', {'category': menu_category.id}) %}

{% block title %}
    {% if entity.title %}
        {{ entity.title }}
    {% else %}
        {{ entity.translate(default_locale, false).title }}<br>
        {{ block("title_no_translation_badge") }}
    {% endif %}
{% endblock %}
{% block buttons %}
    {{ block('back_button') }}
{% endblock %}

{% block right_sidebar %}
    {{ block('changes_details') }}
    {{ block('delete_form') }}
{% endblock %}

src/templates/menu/index.html.twig
{% extends '@TwinElementsAdmin/core/list.html.twig' %}
{% use '@TwinElementsSortable/blocks.html.twig' %}

{% set add_button_link = path('menu_new', {'category': menu_category.id }) %}

{% block title %}{{ menu_category.title }}{% endblock %}
{% block buttons %}
    {{ block('add_button') }}
{% endblock %}

{% block renderChild %}
    {% set actualLvl = lvl %}
    {{ block('list_ul_begin') }}
        {% for child in children %}
            {% set id = child.id %}
            {% set createdAt = child.createdAt %}
            {% set createdBy = child.createdBy %}
            {% set updatedAt = child.updatedAt %}
            {% set updatedBy = child.updatedBy %}

            {{ block('list_li_begin') }}
                    {{ block('id') }}
                    <div class="col">
                        <div class="title">
                            <a href="{{ path('menu_edit', { 'id': child.id, 'category': menu_category.id }) }}">
                                {% if actualLvl > 0 %}
                                    {% for i in 1..actualLvl %}
                                        <span class="arrow-right"></span>
                                    {% endfor %}
                                {% endif %}
                                {{ child.title }}
                                {% if child.title is null %}
                                    <span class="badge badge-warning">{{ "cms.no_translations"|translate_admin }}</span>
                                {% endif %}
                            </a>
                            {% if child.isMegamenu %}
                                <span class="badge badge-info">{{ "menu.megamenu"|translate_admin }}</span>
                            {% endif %}
                        </div>
                    </div>
                    {{ block('changes_box_in_list') }}
                    {{ block('move') }}

                {% if child.children|length > 0 %}
                    {% set lvl = actualLvl + 1 %}
                    {% set children = child.children %}
                    {{ block('renderChild') }}
                {% endif %}
            {{ block('list_li_end') }}
        {% endfor %}
    {{ block('list_ul_end') }}
{% endblock %}

{% block list %}
    {{ block('list_ul_begin') }}
        {{ block('list_li_header_begin') }}
                {{ block('id_header') }}
                <div class="col">{{ "menu.menu"|translate_admin }}</div>
                {{ block('list_changes_header') }}
                {{ block('move_header') }}
        {{ block('list_li_header_end') }}
        {% for menu in menus|filter(menu => menu.parent == null) %}
            {% set id = menu.id %}
            {% set createdAt = menu.createdAt %}
            {% set createdBy = menu.createdBy %}
            {% set updatedAt = menu.updatedAt %}
            {% set updatedBy = menu.updatedBy %}

            {{ block('list_li_begin') }}
                    {{ block('id') }}
                    <div class="col">
                        <div class="title">
                            <a href="{{ path('menu_edit', { 'id': menu.id, 'category': menu_category.id }) }}">
                                <span>{{ menu.title }}</span>
                                {% if menu.title is null %}
                                    <span class="badge badge-warning">{{ "cms.no_translations"|translate_admin }}</span>
                                {% endif %}
                            </a>
                            {% if  menu.isMegamenu %}
                                <span class="badge badge-info">{{ "menu.megamenu"|translate_admin }}</span>
                            {% endif %}
                        </div>
                    </div>
                    {{ block('changes_box_in_list') }}
                    {{ block('move') }}
                {% if menu.children|length > 0 %}
                    {% set lvl = 1 %}
                    {% set children = menu.children %}
                    {{ block('renderChild') }}
                {% endif %}
            {{ block('list_li_end') }}
        {% endfor %}
    {{ block('list_ul_end') }}
{% endblock %}

{% block head_js %}
    {{ block('sortable') }}
{% endblock %}

src/templates/menu/new.html.twig
{% extends '@TwinElementsAdmin/core/details.html.twig' %}

{% block title %}{{ 'menu.add_new_menu_item'|translate_admin }}{% endblock %}
{% block buttons %}
    {% set back_button_link = path('menu_index', {'category': menu_category.id}) %}
    {{ block('back_button') }}
{% endblock %}